# Generated by Django 2.2.11 on 2020-10-29 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
                ('lastsent', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='queuedmail',
            name='sendat',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
