<h2>Graphical installer</h2>
<p>
Installers are available for 32 and 64-bit Linux distributions
and include PostgreSQL, pgAdmin and the StackBuilder utility for installation
of additional packages.
</p>
<p>
<a href="http://www.enterprisedb.com/products/pgdownload.do">Download</a>
the installer from EnterpriseDB for all supported versions.
</p>

<p>
<i>Note:</i> The installers do not integrate with
platform-specific packaging systems.
</p>
