<h2>Cross distribution packages</h2>
<p>
Generic RPM and DEB packages that provide a server-only distribution
are avaliable for some 32 and 64-bit Linux distributions.  These
packages provide a single set of binaries and consistent packaging
across different Linux distributions.  They are designed for server
installation where a GUI is not available and consistency across
multiple distributions is a requirement.
</p>
<p>
<a href="http://www.openscg.com/se/postgresql/packages.jsp">Download</a>
the packages from OpenSCG for all supported versions.
</p>

<p>
<i>Note:</i> The cross distribution packages do not fully integrate with
the platform-specific packaging systems.
</p>
