<h2>Interactive installer by EDB</h2>
<p>
<a href="https://www.enterprisedb.com/downloads/postgres-postgresql-downloads"> Download the installer</a>
 certified by EDB for PostgreSQL 10.x and earlier.
</p>

<p><strong>Note:</strong> Installers for Linux are no longer being product for PostgreSQL 11 and later.
Users are advised to use platform native packages instead.</p>

<p>This installer includes the PostgreSQL server, pgAdmin; a graphical tool for managing and developing
your databases, and StackBuilder; a package manager that can be used to download and install
additional PostgreSQL tools and drivers. Stackbuilder includes management,
integration, migration, replication, geospatial, connectors and other tools.
</p>

<p>
This installer can run in graphical, command line, or silent install modes.
</p>

<p>
The installer is designed to be a straightforward, fast way to get up and running with
PostgreSQL on Linux (Red Hat family Linux including CentOS/Fedora/Scientific/Oracle variants),
Debian GNU/Linux and derivatives, Ubuntu Linux and derivatives, SuSE and OpenSuSE.
</p>

<p>
<em>Advanced users</em> can also download a
<a href="https://www.enterprisedb.com/download-postgresql-binaries">tar.gz archive</a>
of the binaries, without the installer.
This download is intended for users who wish to include PostgreSQL as part of another application installer.
</p>

<p>
<em>Note:</em> The installers do not integrate with
platform-specific packaging systems.
</p>
