# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-05 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_badged'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM events_event WHERE training"),
        migrations.RemoveField(
            model_name='event',
            name='training',
        ),
    ]
