# Generated by Django 2.2.12 on 2020-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_docs_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPageRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_from', models.CharField(max_length=64, unique=True, help_text='Page to redirect from, e.g. "old_page.html"')),
                ('redirect_to', models.CharField(max_length=64, unique=True, help_text='Page to redirect to, e.g. "new_page.html"')),
            ],
            options={
                'verbose_name_plural': 'Doc page redirects',
            },
        ),
    ]
