# Generated by Django 5.2.16 on 2026-07-29 12:45

import django.db.models.deletion
import pgweb.util.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0004_alter_contributor_user"),
        ("core", "0007_usersubmissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="ctype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contributors.contributortype",
                verbose_name="Contributor Type",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "badge",
                    models.CharField(
                        help_text='Title of this badge, e.g. "PGConf.EU 2025 Speaker".',
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the badge page. Generated from the title when the badge is created, and kept fixed after that.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What did the people do who contributed here?",
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL for this contribution, e.g. the conference homepage. (Leave blank when there is no URL.)",
                        max_length=100,
                        null=True,
                        verbose_name="Contribution URL",
                    ),
                ),
                (
                    "imagedata",
                    pgweb.util.fields.ImageBinaryField(
                        blank=True,
                        help_text="Square image, will be auto-scaled to 150×150. JPEG or PNG, up to 1 MB. When left blank, the Slony logo will be used.",
                        max_length=1000000,
                        null=True,
                        verbose_name="Image",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact address (email, URL, other) for people who want to be added as badge holder",
                        max_length=100,
                        null=True,
                        verbose_name="Contact address",
                    ),
                ),
                ("sortorder", models.IntegerField(blank=True, default=100, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        help_text='If no organisations are listed here, please check the <a href="/account/orglist/">organisation list</a> and contact the organisation manager or <a href="mailto:webmaster@postgresql.org">webmaster@postgresql.org</a> if no managers are listed. If your organisation is not listed, you can <a href="/account/edit/organisations/">create it</a>.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("sortorder", "badge"),
            },
        ),
        migrations.CreateModel(
            name="Badgeholder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateField(auto_now_add=True)),
                ("date_retired", models.DateField(blank=True, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contributors.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": (
                    "badge__sortorder",
                    "badge",
                    "user__last_name",
                    "user__first_name",
                ),
            },
        ),
        migrations.AddField(
            model_name="badge",
            name="holders",
            field=models.ManyToManyField(
                blank=True,
                through="contributors.Badgeholder",
                through_fields=("badge", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="badgeholder",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge"
            ),
        ),
    ]
