# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurematrix', '0004_feature_v11'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='v12',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Obsolete'), (3, '?')], default=0, verbose_name='12'),
        ),
    ]
