# Generated by Django 2.2.24 on 2021-09-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurematrix', '0006_feature_v13'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='v14',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Obsolete'), (3, '?')], default=0, verbose_name='13'),
        ),
        migrations.RunSQL("UPDATE featurematrix_feature SET v14=v13"),
    ]
