# Generated by Django 3.2.10 on 2023-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurematrix', '0008_feature_v15'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='v16',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Obsolete'), (3, '?')], default=0, verbose_name='16'),
        ),
        migrations.RunSQL("UPDATE featurematrix_feature SET v16=v15"),
    ]
