# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_block_oauth'),
        ('news', '0003_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstag',
            name='allowed_orgs',
            field=models.ManyToManyField(blank=True, help_text='Organisations allowed to use this tag', to='core.Organisation'),
        ),
        migrations.AddField(
            model_name='newstag',
            name='sortkey',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'ordering': ('sortkey', 'urlname', )},
        )
    ]
