# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='approved',
        ),
        migrations.RunSQL(
            "UPDATE news_newsarticle SET modstate=CASE WHEN approved THEN 2 ELSE 0 END",
            "UPDATE news_newsarticle SET approved=(modstate = 2)",
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='modstate',
            field=models.IntegerField(choices=[(0, 'Created (submitter edits)'), (1, 'Pending moderation'), (2, 'Approved and published')], default=0, verbose_name='Moderation state'),
        ),
    ]
