# Generated by Django 2.2.11 on 2020-09-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_org_emails'),
        ('news', '0005_modstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.OrganisationEmail', verbose_name='Reply email'),
        ),
    ]
