# Generated by Django 2.2.11 on 2020-09-26 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_sending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
