# Generated by Django 5.2.10 on 2026-04-02 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='postedto',
            field=models.JSONField(null=False, blank=True, default=dict)
        ),
        migrations.RunSQL(
            "UPDATE news_newsarticle SET postedto=jsonb_build_object('twitter', true) WHERE tweeted",
            "UPDATE news_newsarticle SET tweeted = true WHERE postedto ? 'twitter'",
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='tweeted',
        ),
    ]
