# Generated by Django 5.2.10 on 2026-04-06 20:14

import django.db.models.deletion
from django.db import migrations, models


def add_record(apps, schema_editor):
    apps.get_model('news', 'PinnedNewsArticle')(pinnedarticle=None).save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_multisocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedNewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinnedtoproviders', models.JSONField(blank=True, default=dict)),
                ('pinnedarticle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newsarticle')),
            ],
        ),
        migrations.RunPython(add_record),
    ]
