# Generated by Django 5.2.10 on 2026-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newspostingembargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnednewsarticle',
            name='uniqueness',
            field=models.GeneratedField(db_persist=True, expression=models.Value(1), output_field=models.IntegerField(), unique=True),
        ),
    ]
