# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_block_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='mailtemplate',
            field=models.CharField(choices=[('default', 'Default template'), ('pgproject', 'PostgreSQL project news')], default='default', max_length=50, verbose_name='Mail template'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='fromnameoverride',
            field=models.CharField(max_length=100, null=False, blank=True,
                                   verbose_name='From name override',
                                   help_text='Always set the sender name of news email to this'),
        ),
    ]
