# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_block_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='mailtemplate',
            field=models.CharField(choices=[('default', 'Default template'), ('pgproject', 'PostgreSQL project news')], default='default', max_length=50),
        ),
    ]
