# Generated by Django 2.2.11 on 2020-09-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='phone',
        ),
        migrations.CreateModel(
            name='OrganisationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organisation')),
                ('added', models.DateTimeField(null=False, auto_now_add=True)),
            ],
            options={
                'ordering': ('org', 'address'),
                'unique_together': {('org', 'address')},
            },
        ),
    ]
