# Generated by Django 2.2.11 on 2021-05-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_org_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='relnotes',
        ),
    ]
