# Generated by Django 3.2.11 on 2022-06-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_version_relnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='docsgit',
            field=models.CharField(blank=True, help_text='The git hash of the loaded docs, for devel version', max_length=40),
        ),
    ]
