# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_lowercase_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAuthConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentgiven', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAuthOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(help_text='Name of the organisation', max_length=100)),
                ('require_consent', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunSQL("INSERT INTO account_communityauthorg (orgname, require_consent) VALUES ('PostgreSQL Global Development Group', false)", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='communityauthconsent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CommunityAuthOrg'),
        ),
        migrations.AddField(
            model_name='communityauthconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityauthsite',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.CommunityAuthOrg'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='communityauthconsent',
            unique_together=set([('user', 'org')]),
        ),
    ]
