# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-25 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cauth_consent'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE account_communityauthlastlogin (
   user_id int NOT NULL REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED ON DELETE CASCADE,
   site_id int NOT NULL REFERENCES account_communityauthsite (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
   lastlogin timestamptz NOT NULL,
   logincount bigint NOT NULL,
   CONSTRAINT account_communityauthlastlogin_pkey PRIMARY KEY (user_id, site_id)
)"""),
    ]
