# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-06 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_cauth_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=100)),
                ('sentat', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('email', ),
            },
        ),
        migrations.DeleteModel(
            name='EmailChangeToken',
        ),
    ]
