# Generated by Django 3.2.14 on 2023-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_cooloff_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityauthorg',
            name='orgname',
            field=models.CharField(help_text='Name of the organisation', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='communityauthsite',
            name='name',
            field=models.CharField(help_text="Note that the value in this field is shown on the login page, so make sure it's user-friendly!", max_length=100, unique=True),
        ),
    ]
