# Generated by Django 4.2.11 on 2025-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_cauth_unique_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityauthsite',
            name='version',
            field=models.IntegerField(choices=[(2, 2), (3, 3)], default=2),
        ),
    ]
