# Generated by Django 5.2.10 on 2026-05-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_communityauthsite_version'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityauthsite',
            name='require_groups',
            field=models.ManyToManyField(blank=True, help_text='Require membership in at least one of the specified groups in order to log in', to='auth.group'),
        ),
    ]
